-- ARCHIVO LEGACY: NO EJECUTAR EN SUPABASE SQL EDITOR.
--
-- La implementacion activa de ligas publicas vive en el historial de
-- `supabase/migrations`. Ejecutar una copia manual antigua puede restaurar
-- politicas globales o permitir que el navegador altere precios de pedidos.
--
-- Para instalar o actualizar usa las migraciones versionadas y confirma con:
--   supabase/tests/public_quote_submission_security.sql
